FROM beevelop/nodejs-python:latest

RUN mkdir -p /var/www/ria
WORKDIR /var/www/ria

ENV NODE_ENV production

COPY . .
RUN npm install --production

RUN touch .env

CMD ["/var/www/ria/bin/hubot"]
